/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.3.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "spinnaker-contrib-playground"

include("kubernetes-azure-spinnaker")

include("kubernetes-azure-spinnaker-db-mysql")

include("kubernetes-azure-spinnaker-db-postgres")

include("pulumi-multicloud-compute")
